Validate Page instance in afterExecute method
## Description
`Magento\Catalog\Controller\Category\View::execute()` does not always return a view page result. In some cases Magento can return other controller result types, such as `Magento\Framework\Controller\Result\Forward`.

The current plugin assumes that the result passed to `afterExecute()` is always a page result and calls:

```php
$page->getLayout()

This causes a fatal error when the category controller returns a forward result, because Forward does not implement getLayout().

## Production error example
We observed this in production on Magento 2.4.8:
```
[2026-05-15T08:37:48.501563+00:00] main.CRITICAL:
Error: Call to undefined method Magento\Framework\Controller\Result\Forward\Interceptor::getLayout()
in /var/www/html/app/code/Mageplaza/AjaxLayer/Plugin/Controller/Category/View.php:57
```
Relevant stack trace:
```
#0 vendor/magento/framework/Interception/Interceptor.php(146):
   Mageplaza\AjaxLayer\Plugin\Controller\Category\View->afterExecute()

#1 vendor/magento/framework/Interception/Interceptor.php(153):
   Smartwave\Porto\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}()

#3 vendor/magento/framework/App/Action/Action.php(111):
   Smartwave\Porto\Controller\Category\View\Interceptor->execute()
```